src/Complementary/RegistrationWeb/Models/SharedViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace RegistrationWeb.Models
{
    public class SharedViewModel
    {
        ///////////////  Step 1  ////////////////
        public DateTime ExamDate { get; set; }
        public string ExamLocation { get; set; }
        /// <summary>
        /// หลักสูตรที่สอบ 
        /// ภาค ก : "OCSCa"
        /// </summary>
        public string ExamType { get; set; }
        /// <summary>
        /// รอบการสอบ 
        /// 1: เช้า (9.00 - 12.00 น.)
        /// 2: บ่าย (13.00 - 16.00 น.)
        /// </summary>
        public int ExamPeriod { get; set; }

        ///////////////  Step 2  ////////////////
        public string InitialName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public DateTime BirthDate { get; set; }
        public string PID { get; set; }
        public string Address { get; set; }
        public string PhoneNum { get; set; }
        public string Email { get; set; }

        ////////////// Step 3  /////////////////
        /// <summary>
        /// วิธีการชำระเงิน
        /// 1 : Bill
        /// 2 : Counter-Service
        /// 3 : Credit card
        /// 4 : Online banking
        /// </summary>
        public int PaymentMethod { get; set; }

        ////////////// Step 4  /////////////////

        ////////////// Step 5  /////////////////
        public string RegisterCode { get; set; }
    }
}

src/Complementary/RegistrationWeb/Controllers/CertificatedController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RegistrationWeb.Controllers
{
    public class CertificatedController : Controller
    {
        // GET: Certificated
        public ActionResult Certificated()
        {
            return View();
        }
        public ActionResult CertificatedDetail()
        {
            ViewBag.Url = Request.Url.ToString().ToLower();
            return View();
        }
    }
}

src/Complementary/RegistrationWeb/Controllers/PaymentCodeController.cs
using RegistrationWeb.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RegistrationWeb.Controllers
{
    public class PaymentCodeController : Controller
    {
        // GET: PaymentCode
        public ActionResult PaymentCode()
        {
            return View(new SharedViewModel());
        }
    }
}

src/Complementary/RegistrationWeb/Controllers/RegisterController.cs
using RegistrationWeb.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RegistrationWeb.Controllers
{
    public class RegisterController : Controller
    {
        public ActionResult Index()
        {
            var model = new SharedViewModel();
            model.ExamDate = DateTime.Today.AddDays(1);
            return View(model);
        }

        public ActionResult PersonalDetail(SharedViewModel model)
        {
            return View(model);
        }

        public ActionResult Payment(SharedViewModel model)
        {
            model.RegisterCode = DateTime.Now.Ticks.ToString().Substring(12);
            return View(model);
        }

        public ActionResult ConfirmPayment(SharedViewModel model)
        {
            switch (model.PaymentMethod)
            {
                case 1:
                    return View("ConfirmByBank", model);
                case 2:
                    return View("ConfirmByCounterService", model);
                case 3:
                    return View("ConfirmByCreditCard", model);
                case 4:
                    return View("ConfirmByOnlineBanking", model);
                default:
                    return View("ConfirmByBank", model);
            }
        }

        public ActionResult ConfirmByBank(SharedViewModel model)
        {
            return View();
        }

        public ActionResult ConfirmByCounterService(SharedViewModel model)
        {
            return View();
        }

        public ActionResult ConfirmByCreditCard(SharedViewModel model)
        {
            return View();
        }

        public ActionResult ConfirmByOnlineBanking(SharedViewModel model)
        {
            return View();
        }

        public ActionResult HowToPay(SharedViewModel model)
        {
            return View();
        }

        public ActionResult Invoice(SharedViewModel model)
        {
            var expiredDate = 6;
            var amount = 300;
            var invoiceId = 68462035465;

            ViewBag.InvoiceId = invoiceId;
            ViewBag.ExpiredDate = DateTime.Now.AddHours(expiredDate);
            ViewBag.Amount = amount;
            return View(model);
        }

        public ActionResult PrintExamCard(SharedViewModel model)
        {
            //SharedViewModel data = new SharedViewModel
            //{
            //    PID = "OCSC001",
            //    FirstName = "OCSC001",
            //    LastName = "LastName",
            //    Address = "xoxoxoxoxoxo",
            //    BirthDate = DateTime.Now,
            //    Email = "xxx@xxx.com",
            //    ExamDate = DateTime.Now,
            //    ExamLocation = "KKU",
            //    ExamPeriod = 1,
            //    ExamType = "OCSCa",
            //    PaymentMethod = 3,
            //    PhoneNum = "0123456789",
            //    RegisterCode = "13579",
            //};
            //RegisterToEExam(model);

            //Hack: Mock data
            //model.RegisterCode = "5DS3A14e" + DateTime.Now.Ticks;

            ViewBag.ExamTypeText = string.Empty;
            ViewBag.ExamPeriodText = string.Empty;

            if (!string.IsNullOrEmpty(model.FirstName))
            {
                if (model.ExamType == "OCSCa") ViewBag.ExamTypeText = "ภาค ก";
                if (model.ExamPeriod == 1) ViewBag.ExamPeriodText = "เช้า (9.00 - 12.00 น.)";
                else if (model.ExamPeriod == 2) ViewBag.ExamPeriodText = "(13.00 - 16.00 น.)";

                RegisterToEExam(model);
            }
            else
            {
                //HACK : mock data for print exam card
                model = new SharedViewModel
                {
                    PID = "OCSC001",
                    FirstName = "สมชาย",
                    LastName = "สายเสมอ",
                    Address = "xoxoxoxoxoxo",
                    BirthDate = DateTime.Now,
                    Email = "xxx@xxx.com",
                    ExamDate = DateTime.Now,
                    ExamLocation = "KKU",
                    ExamPeriod = 1,
                    ExamType = "OCSCa",
                    PaymentMethod = 3,
                    PhoneNum = "0123456789",
                    RegisterCode = "13579",
                };
                if (model.ExamType == "OCSCa") ViewBag.ExamTypeText = "ภาค ก";
                if (model.ExamPeriod == 1) ViewBag.ExamPeriodText = "เช้า (9.00 - 12.00 น.)";
                else if (model.ExamPeriod == 2) ViewBag.ExamPeriodText = "(13.00 - 16.00 น.)";
            }
            
            return View(model);
        }

        public ActionResult ExamCard(SharedViewModel model)
        {
            ViewBag.ExamTypeText = string.Empty;
            ViewBag.ExamPeriodText = string.Empty;

            if (model.ExamType == "OCSCa") ViewBag.ExamTypeText = "ภาค ก";
            if (model.ExamPeriod == 1) ViewBag.ExamPeriodText = "เช้า (9.00 - 12.00 น.)";
            else if (model.ExamPeriod == 2) ViewBag.ExamPeriodText = "(13.00 - 16.00 น.)";
            return View(model);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="data"></param>
        /// <param name="schoolID"></param>
        private void RegisterToEExam(SharedViewModel data)
        {
            #region Convertion
            //แปลข้อมูล TestPerson เป็น Registraion

            RegistrationService.Register testReg = null;
            testReg = new RegistrationService.Register
            {
                //Person section
                PID = data.PID,
                FirstName = data.FirstName,
                LastName = data.LastName,
                BirthDate = data.BirthDate,

                //TestRegistration section
                ApplicationId = data.PID + data.RegisterCode,

                //LicenseType set below this block
                QuizLanguage = "TH",
                IsListenQuiz = false,
                //AppointDateTime set below this block
                //ExpireDateTime = DateTime.Now.AddDays(_ExpireDay),
                //ApprovedDateTime = DateTime.Now,
                //CourseType = item.CouseType != null ? item.CouseType : "No course",
                CourseType = "No course",
                //SchoolId = Convert.ToInt32(item.CERT_NO),
                SchoolId = 2071,
                ExamNumber = data.PID,
                //ExamNumber = 0,
                AppointDateTime = data.ExamDate,
                ExpireDateTime = data.ExamDate.AddYears(10),
                Status = "APPROVED",
                ApprovedDateTime = DateTime.Now,
                LicenseType = data.ExamType,
                ForPractice = false,
                ForTestSystem = false,
                PhoneNumber = data.PhoneNum,
                Address = data.Address,
                Title = data.InitialName             
            };
            #endregion Convertion

            var wcf = new RegistrationService.RegistrationServiceClient();

            RegistrationService.Register[] arr = new RegistrationService.Register[] { testReg };
            wcf.RegisterNewPerson(arr);
        }
    }
}

src/Complementary/RegistrationWeb/Views/Shared/_BlankLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="container body-content">
        <br />
        @RenderBody()
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

src/Complementary/RegistrationWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="wrapper">
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a href="/Home/Index"><img height="50" src="~/Asset/images/Logo_Customer.png" /></a>
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("หน้าหลัก", "Index", "Home")</li>
                        <li>@Html.ActionLink("สมัครสอบ", "Index", "Register")</li>
                        <li>@Html.ActionLink("กรอกรหัสชำระเงิน", "PaymentCode", "PaymentCode")</li>
                        <li>@Html.ActionLink("ดูผลสอบ", "Certificated", "Certificated")</li>

                    </ul>
                    @Html.Partial("_LoginPartial")
                </div>
            </div>
        </div>
        <div class="container body-content body">
            @RenderBody()
        </div>
        <footer class="footer text-center">
            <span>สำนักงานคณะกรรมการข้าราชการพลเรือน (สำนักงาน ก.พ.)</span>
            <br />
            <span>Office of the Civil Service Commission (OCSC)</span>     
        </footer>
    </div>


    @Scripts.Render("~/bundles/jquery")
    <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>